spring:
  application:
    name: UserClient
server:
  port: 2101
eureka:
  client:
    service-url:
      defaultZone: http://name:admin123@localhost:7000/eureka/
  instance:
      instance-id: ${spring.application.name}:${server.port}
      prefer-ip-address: true
      #表示 Eureka Client 向 Eureka Server 发送心跳的频率（默认 30 秒），如果在 lease-expiration-duration-in-seconds
      #指定的时间内未收到心跳，则移除该实例。
      lease-renewal-interval-in-seconds: 5
      #表示 Eureka Server 在接收到上一个心跳之后等待下一个心跳的秒数（默认 90 秒），若不能在指定时间内收到心跳，则移除此实例，并禁止此实例的流量。
      lease-expiration-duration-in-seconds: 15

feign:
  hystrix:
    enabled: true #是否开启断路器

OrderServer:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
