server:
  port: 2102

spring:
  application:
    name: OrderServer                        # 指定发布的微服务名（以后调用时，只需该名称即可访问该服务）

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://name:admin123@127.0.0.1:7000/eureka/

#      这里是注册集群服务
#      defaultZone: http://name:admin123@127.0.0.1:7001/eureka/,http://name:admin123@127.0.0.1:7002/eureka/  # 指定服务注册中心的地址